# Generated by Django 3.2.4 on 2021-08-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_field',
            field=models.CharField(default='NA', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
