# Generated by Django 3.2.4 on 2021-08-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210818_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='new_field',
            new_name='address',
        ),
    ]
